var target;
var starter = args[0];

while(true){
    // if(starter){
    //     target = "n00dles";
    //     hack(target);
    // }
	// else{
    target = "joesguns";
    weaken(target, {threads : starter});
    if(getServerMoneyAvailable(target) < getServerMaxMoney(target)*.5){
        grow(target, {threads : starter});
    }
    else{
        hack(target, {threads : starter});
    }
	// }
    
}